package gym.login.system;

import static gym.login.system.DailyReport.day;
import static gym.login.system.DailyReport.month;
import static gym.login.system.DailyReport.year;
import static gym.login.system.Gym_Login_System.EmployeesID;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author emtin
 */
public class ManagmentReport2 extends javax.swing.JFrame {

    /**
     * Creates new form ManagmentReport2
     */
    public ManagmentReport2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ReportE = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        inputday = new javax.swing.JTextField();
        inputmonth = new javax.swing.JTextField();
        inputyear = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportResult = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        ReportE.setColumns(20);
        ReportE.setRows(5);
        jScrollPane1.setViewportView(ReportE);

        jScrollPane3.setViewportView(jTextPane2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputdayActionPerformed(evt);
            }
        });
        getContentPane().add(inputday, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 170, -1));

        inputmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputmonthActionPerformed(evt);
            }
        });
        getContentPane().add(inputmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 170, -1));

        inputyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputyearActionPerformed(evt);
            }
        });
        getContentPane().add(inputyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 170, -1));

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        ReportResult.setColumns(20);
        ReportResult.setRows(5);
        jScrollPane2.setViewportView(ReportResult);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 300, 390));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/day background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputdayActionPerformed
        String day = inputday.getText();
        DailyReport.setDay(day);

    }//GEN-LAST:event_inputdayActionPerformed

    private void inputyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputyearActionPerformed
        // TODO add your handling code here:
        String year = inputyear.getText();
        DailyReport.setYear(year);
    }//GEN-LAST:event_inputyearActionPerformed

    private void inputmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputmonthActionPerformed

        // TODO add your handling code here:
        String month = inputmonth.getText();
        DailyReport.setMonth(month);

    }//GEN-LAST:event_inputmonthActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:

        Random randomNum = new Random();
        int [] ID = Gym_Login_System.getEmployeesID(EmployeesID);

        for (int i = 0; i < ID.length; i++) {
            int hour = randomNum.nextInt(10) + 1;
            int minutes = randomNum.nextInt(60);

            ReportResult.append("- - - - - - - - - - - - - - - - - - - - - - -  " + "\n"
                    + " Employee Attendance Report " + "\n"
                    + "- - - - - - - - - - - - - - - - - - - - - - -  " + "\n"
                    + "Employee ID : " + ID[i] + "" + "\n"
                    + "Time Attendance :             Date: " + "\n"
                    + "- - - - - - - - - - - - - - - - - - - - - - -  " + "\n");

            for (int j = 0; j < 1; j++) {
                ReportResult.append("      " + hour + ":" + minutes + "                   " + inputyear.getText() + "-" + inputmonth.getText() + "-" + inputday.getText() + "\n" + "\n");

            }

        }
        ReportResult.append("\n" + "- - - -  This report is for viewing, not for print - - - -  ");



    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagmentReport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagmentReport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagmentReport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagmentReport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagmentReport2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JTextArea ReportE;
    private javax.swing.JTextArea ReportResult;
    private javax.swing.JTextField inputday;
    private javax.swing.JTextField inputmonth;
    private javax.swing.JTextField inputyear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
